# Site settings
title: Haibo Li
email: haibolee1729@gmail.com
description: Personal webpage of Dr. Haibo Li
baseurl: ""
url: "https://machealb.github.io/"


# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Haibo Li<br/>
  <!-- Research Fellow <br/> -->
  University of Melbourne

location: >
  G82, Peter Hall Building (160)<br/>
  University of Melbourne<br/>
  Melbourne VIC 3010, Australia

contact: >
  <a href="mailto:haibolee1729@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Haibo via email</a><br/>
  <!-- <a href="https://github.com/sbryngelson/academic-website-template" target="_blank"><i class="fa fa-github fa-1x"></i> Use this template for personal website.</a> -->


# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
  # - name: talks
  - name: teaching
  # - name: team
  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

markdown_ext: "markdown,mkdown,mkdn,mkd,md"  # 让 Jekyll识别.tex 文件并交给转换器

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Li
  first_name: [Haibo]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile