
name:
  # Reviewer of journals
  journals:
    - name1: Reviewer for Mathematical Reviews (No. 161348)
    - name1: SIAM Journal on Matrix Analysis and Applications
    - name1: BIT Numerical Mathematics

  # Reviewer of conferences
  conferences:
    - name2: The 13th International Conference on Electronics, Communications and Networks (CECNet 2023), 2023
    - name2: The International Conference for High Performance Computing, Networking, Storage, and Analysis (SC22), 2022

  # Reviewer of grants
  grants:
    - name3: International reviewer for Czech Science Foundation (Czech Republic), 2024
